AWSTemplateFormatVersion: '2010-09-09'
Description: Test Stack - RDS
Resources:

  TestDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: testrds
      AllocatedStorage: '20'
      PubliclyAccessible: true
      MultiAZ: false
      StorageEncrypted: false
      StorageType: gp2
      BackupRetentionPeriod: '0'
      DBInstanceClass: db.t2.medium
      Engine: MySQL
      EngineVersion: "8.0.16"
      MasterUsername: 'admin'
      MasterUserPassword: 'test1234'
    
      
